from gemeinsam import *

b("da01", "Was ist der Unterschied zwischen var, final und const?", "var: veränderbar. final: wird einmal zugewiesen (zur Laufzeit). const: steht schon beim Kompilieren fest und ist tief unveränderlich.")
b("da02", "Was bedeutet Null-Safety?", "Ein Typ wie String kann nie null sein. Nur String? darf null sein. Der Compiler zwingt dich, null vorher zu prüfen.")
b("da03", "Was macht der Operator ?? ?", "Liefert den linken Wert, wenn er nicht null ist, sonst den rechten: name ?? \"Gast\".")
b("da04", "Was macht ?. ?", "Ruft nur auf, wenn das Objekt nicht null ist, sonst ergibt der Ausdruck null: name?.length.")
b("da05", "Was bedeutet late?", "Die Variable wird erst später, aber garantiert vor der ersten Benutzung gesetzt. Sonst gibt es einen Laufzeitfehler.")
b("da06", "Was ist ein Future?", "Ein Wert, der erst später da ist, z. B. das Ergebnis einer Netzwerkanfrage. Mit await wartet man darauf (nur in async-Funktionen).")
b("da07", "Was ist ein Stream?", "Eine Folge von Werten über die Zeit, z. B. Datenbank-Änderungen. Mit listen oder await for verarbeitet man sie.")
b("da08", "Was sind benannte Parameter?", "Parameter in geschweiften Klammern, die man beim Aufruf mit Namen angibt. Mit required muss man sie angeben.", "void gruss({required String name, int alter = 0}) {}")
b("da09", "Was ist der Unterschied zwischen StatelessWidget und StatefulWidget?", "Stateless hat keinen eigenen veränderlichen Zustand. Stateful hat ein State-Objekt und baut sich mit setState() neu.")
b("da10", "Was ist ein Record in Dart?", "Mehrere Werte in einem, ohne eigene Klasse: (int, String) paar = (1, \"a\"); Zugriff mit paar.$1 oder über Namen.")
b("da11", "Was ist ein Mixin?", "Ein Baustein mit Methoden, den man mit with in Klassen einmischt, ohne von ihm zu erben.")
b("da12", "Was ist eine Extension?", "Fügt einer vorhandenen Klasse neue Methoden hinzu, ohne sie zu ändern.", "extension Doppelt on int {\n  int get doppelt => this * 2;\n}")
b("da13", "Was macht der Kaskaden-Operator ..?", "Ruft mehrere Methoden auf demselben Objekt auf und liefert am Ende das Objekt selbst.", "final liste = <int>[]..add(1)..add(2);")
b("da14", "Was ist eine sealed class?", "Eine Klasse, deren Unterklassen alle in derselben Datei stehen. switch kann dann prüfen, ob alle Fälle behandelt sind.")
b("da15", "Was ist der Spread-Operator ...?", "Setzt alle Elemente einer Liste in eine andere ein: [...a, ...b].")

a("da30", "print(7 ~/ 2);\nprint(7 / 2);", "3\n3.5", ["3\n3.5", "3.5\n3.5", "3\n3", "3.5\n3"], "~/ teilt ganzzahlig, / liefert immer double.")
a("da31", "String? name;\nprint(name ?? 'Gast');", "Gast", ["Gast", "null", "Fehler", "name"], "name ist null, also nimmt ?? den rechten Wert.")
a("da32", "String? name;\nprint(name?.length);", "null", ["null", "0", "Fehler", "Gast"], "?. bricht bei null ab und liefert null.")
a("da33", "var name = 'Dart';\nprint('Hallo $name, ${name.length} Buchstaben');", "Hallo Dart, 4 Buchstaben", ["Hallo Dart, 4 Buchstaben", "Hallo $name, 4 Buchstaben", "Hallo Dart, name.length Buchstaben", "Fehler"], "$name setzt die Variable ein, ${…} einen ganzen Ausdruck.")
a("da34", "final liste = [1, 2, 3];\nliste.add(4);\nprint(liste);", "[1, 2, 3, 4]", ["[1, 2, 3, 4]", "Fehler", "[1, 2, 3]", "[4]"], "final verbietet nur eine neue Zuweisung. Die Liste selbst darf sich ändern.")
a("da35", "final z = [1, 2, 3, 4];\nprint(z.where((x) => x.isEven).map((x) => x * 10).toList());", "[20, 40]", ["[20, 40]", "[10, 30]", "[2, 4]", "(20, 40)"], "where filtert die geraden Zahlen, map multipliziert.")
a("da36", "final z = [1, 2, 3, 4];\nprint(z.where((x) => x > 1).map((x) => x * 10));", "(20, 30, 40)", ["(20, 30, 40)", "[20, 30, 40]", "Instance of 'Iterable'", "Fehler"], "Ohne toList() ist das Ergebnis ein Iterable und wird mit runden Klammern ausgegeben.")
a("da37", "final z = [3, 1, 2];\nprint(z.fold<int>(0, (summe, x) => summe + x));", "6", ["6", "0", "[3, 1, 2]", "312"], "fold geht durch alle Elemente und sammelt ein Ergebnis, hier die Summe.")
a("da38", "final a = [1, 2];\nfinal b = [0, ...a, 3];\nprint(b);", "[0, 1, 2, 3]", ["[0, 1, 2, 3]", "[0, [1, 2], 3]", "[1, 2, 0, 3]", "Fehler"], "... setzt die Elemente von a einzeln ein.")
a("da39", "final mitBonus = true;\nfinal punkte = [10, 20, if (mitBonus) 5];\nprint(punkte.length);", "3", ["3", "2", "Fehler", "35"], "Collection-if fügt das Element nur hinzu, wenn die Bedingung stimmt.")
a("da40", "final m = {'a': 1, 'b': 2};\nm['c'] = 3;\nprint(m.keys.toList());", "[a, b, c]", ["[a, b, c]", "[1, 2, 3]", "{a, b, c}", "Fehler"], "keys liefert die Schlüssel, toList macht eine Liste daraus.")
a("da41", "int doppelt(int x) => x * 2;\nprint(doppelt(doppelt(5)));", "20", ["20", "10", "25", "Fehler"], "=> ist die Kurzform für { return …; }.")
a("da42", "void gruss({required String name, String gruss = 'Hallo'}) {\n  print('$gruss $name');\n}\ngruss(name: 'Lea');", "Hallo Lea", ["Hallo Lea", "Lea Hallo", "null Lea", "Fehler"], "Benannte Parameter: gruss hat einen Standardwert.")
a("da43", "final sb = StringBuffer()\n  ..write('a')\n  ..write('b');\nprint(sb.toString());", "ab", ["ab", "a", "b", "Fehler"], "Mit .. ruft man mehrere Methoden auf demselben Objekt auf.")
a("da44", "final (x, y) = (3, 4);\nprint(x * y);", "12", ["12", "7", "(3, 4)", "Fehler"], "Ein Record wird in zwei Variablen zerlegt (Destructuring).")
a("da45", "(String, int) info() => ('Mia', 16);\nfinal r = info();\nprint('${r.$1} ist ${r.$2}');", "Mia ist 16", ["Mia ist 16", "$1 ist $2", "(Mia, 16)", "Fehler"], "Felder eines Records ohne Namen heißen $1, $2 …")
a("da46", "final wert = 7;\nfinal text = switch (wert) {\n  < 0 => 'negativ',\n  0 => 'null',\n  >= 1 && <= 9 => 'einstellig',\n  _ => 'groß',\n};\nprint(text);", "einstellig", ["einstellig", "groß", "null", "negativ"], "Switch-Ausdruck mit Mustern: Der erste passende Fall gewinnt, _ ist der Rest.")
a("da47", "class Zaehler {\n  int _n = 0;\n  int get n => _n;\n  void plus() => _n++;\n}\n\nvoid main() {\n  final z = Zaehler()\n    ..plus()\n    ..plus();\n  print(z.n);\n}", "2", ["2", "0", "1", "Fehler"], "Der Unterstrich macht _n privat (für die Datei). Von außen liest man über den Getter n.")
a("da48", "Future<int> laden() async => 42;\n\nvoid main() async {\n  print('A');\n  final x = await laden();\n  print(x);\n}", "A\n42", ["A\n42", "42\nA", "A\nInstance of 'Future<int>'", "A"], "await wartet auf das Future und liefert den Wert.")
a("da49", "void main() {\n  print('1');\n  Future(() => print('2'));\n  print('3');\n}", "1\n3\n2", ["1\n3\n2", "1\n2\n3", "2\n1\n3", "1\n3"], "Ein Future läuft erst, wenn der aktuelle Code fertig ist. Deshalb kommt 2 zuletzt.")
a("da50", "extension Doppelt on int {\n  int get doppelt => this * 2;\n}\n\nvoid main() {\n  print(21.doppelt);\n}", "42", ["42", "21", "2121", "Fehler"], "Die Extension fügt int einen Getter hinzu.")
a("da51", "final namen = ['Tim', 'Anna', 'Bo'];\nnamen.sort((a, b) => a.length.compareTo(b.length));\nprint(namen);", "[Bo, Tim, Anna]", ["[Bo, Tim, Anna]", "[Anna, Bo, Tim]", "[Tim, Anna, Bo]", "[Anna, Tim, Bo]"], "Der Vergleich sortiert nach der Länge: 2, 3, 4.")
a("da52", "print([1, 2, 3].contains(2) && 'abc'.startsWith('b'));", "false", ["false", "true", "Fehler", "null"], "'abc' beginnt mit a, nicht mit b.")
a("da53", "int? zahl = int.tryParse('12a');\nprint(zahl ?? -1);", "-1", ["-1", "12", "null", "Fehler"], "tryParse liefert null statt eines Fehlers, wenn der Text keine Zahl ist.")
a("da54", "sealed class Form {}\nclass Kreis extends Form { final double r; Kreis(this.r); }\nclass Quadrat extends Form { final double a; Quadrat(this.a); }\n\ndouble flaeche(Form f) => switch (f) {\n  Kreis(r: final r) => 3 * r * r,\n  Quadrat(a: final a) => a * a,\n};\n\nvoid main() {\n  print(flaeche(Quadrat(3)));\n}", "9.0", ["9.0", "9", "27.0", "Fehler"], "Bei sealed classes prüft switch, dass alle Unterklassen behandelt sind. a * a mit double ergibt 9.0.")

l("da70", "Ergänze, damit name auch null sein darf.", "String___ name;\nprint(name ?? 'leer');", "?", ["?", "!", "*", "&"], "leer", "Ein ? hinter dem Typ erlaubt null.")
l("da71", "Ergänze, um auf das Ergebnis zu warten.", "Future<String> holen() async => 'Daten';\n\nvoid main() async {\n  final d = ___ holen();\n  print(d);\n}", "await", ["await", "async", "yield", "then"], "Daten", "await wartet auf ein Future und liefert dessen Wert.")
l("da72", "Ergänze die Methode, die nur passende Elemente behält.", "final w = ['Hi', 'Dart', 'ok', 'Code'];\nprint(w.___((s) => s.length > 2).toList());", "where", ["where", "map", "filter", "any"], "[Dart, Code]", "In Dart heißt filtern where (filter gibt es nicht).")
l("da73", "Ergänze, damit die Variable nie neu zugewiesen werden kann (Wert erst zur Laufzeit bekannt).", "___ jetzt = DateTime(2026, 1, 1);\nprint(jetzt.year);", "final", ["final", "const", "static", "late"], "2026", "final: genau eine Zuweisung, der Wert darf zur Laufzeit entstehen. (DateTime(...) ist kein const-Konstruktor.)")
l("da74", "Ergänze den Operator für Ganzzahl-Division.", "print(17 ___ 5);", "~/", ["~/", "/", "//", "%"], "3", "~/ teilt ganzzahlig. / gibt 3.4, % gibt den Rest 2.")
l("da75", "Ergänze das Schlüsselwort für einen Pflicht-Parameter mit Namen.", "void bestellen({___ String produkt, int menge = 1}) {\n  print('$menge× $produkt');\n}\n\nvoid main() {\n  bestellen(produkt: 'Klicker');\n}", "required", ["required", "final", "late", "const"], "1× Klicker", "Benannte Parameter sind optional, außer man schreibt required davor.")

speichern("dart_grundlagen", "Dart & Flutter Basics", "dart", "Grundlagen",
          "Null-Safety, Collections, Funktionen, Klassen, async/await, Records, Pattern Matching und Flutter-Begriffe.",
          "paket_dart")
