from gemeinsam import *

b("js01", "Was ist der Unterschied zwischen let, const und var?", "let: veränderbar, gilt im Block. const: keine neue Zuweisung, gilt im Block. var: alt, gilt in der ganzen Funktion. Heute nimmt man let und const.")
b("js02", "Was ist der Unterschied zwischen == und ===?", "=== vergleicht Wert und Typ (\"5\" === 5 ist false). == wandelt vorher um (\"5\" == 5 ist true). Fast immer === benutzen.")
b("js03", "Was ist undefined und was ist null?", "undefined: Es wurde nie ein Wert gesetzt. null: bewusst „kein Wert“.")
b("js04", "Was ist eine Arrow Function?", "Eine kurze Funktionsschreibweise: (x) => x * 2. Sie hat kein eigenes this.")
b("js05", "Was ist ein Template-String?", "Ein String in Backticks, in den man mit ${…} Ausdrücke einsetzt.", "`Hallo ${name}!`")
b("js06", "Was ist ein Objekt in JavaScript?", "Eine Sammlung von Schlüssel-Wert-Paaren in geschweiften Klammern.", "const hund = { name: \"Rex\", alter: 3 };")
b("js07", "Was ist ein Promise?", "Ein Platzhalter für einen Wert, der später kommt (z. B. aus dem Netz). Mit await oder .then() kommt man an den Wert.")
b("js08", "Was macht async/await?", "Eine async-Funktion gibt immer ein Promise zurück. Darin wartet await auf ein Promise, ohne die Seite zu blockieren.")
b("js09", "Was ist das DOM?", "Die Baumstruktur der Webseite, die JavaScript lesen und ändern kann, z. B. mit document.querySelector().")
b("js10", "Was ist Destructuring?", "Werte aus Objekten oder Arrays direkt in Variablen holen.", "const { name, alter } = hund;\nconst [erstes, zweites] = liste;")
b("js11", "Was ist der Spread-Operator ...?", "Verteilt die Elemente eines Arrays oder Objekts: [...a, ...b] oder { ...alt, name: \"neu\" }.")
b("js12", "Was ist „truthy“ und „falsy“?", "Falsy sind false, 0, \"\", null, undefined und NaN. Alles andere gilt in Bedingungen als wahr (truthy), auch \"0\" und [].")
b("js13", "Was macht JSON.stringify bzw. JSON.parse?", "stringify wandelt ein Objekt in einen JSON-Text um, parse macht aus dem Text wieder ein Objekt.")

a("js30", "console.log(\"5\" + 3);\nconsole.log(\"5\" - 3);", "53\n2", ["53\n2", "8\n2", "53\n53", "8\n-2"], "+ mit einem String hängt an. - gibt es für Strings nicht, also wird \"5\" in eine Zahl umgewandelt.")
a("js31", "console.log(\"5\" == 5, \"5\" === 5);", "true false", ["true false", "true true", "false false", "false true"], "== wandelt um, === nicht.")
a("js32", "console.log(typeof 42, typeof \"42\", typeof null);", "number string object", ["number string object", "number string null", "int string null", "number number object"], "typeof null ist \"object\": ein alter Fehler in JavaScript, der nie behoben wurde.")
a("js33", "console.log(0.1 + 0.2 === 0.3);", "false", ["false", "true", "0.3", "NaN"], "Kommazahlen sind binär nicht exakt: 0.1 + 0.2 ist 0.30000000000000004.")
a("js34", "const z = [1, 2, 3, 4];\nconsole.log(z.filter(x => x % 2 === 0).map(x => x * 10));", "[ 20, 40 ]", ["[ 20, 40 ]", "[ 10, 30 ]", "[ 2, 4 ]", "60"], "filter behält gerade Zahlen, map multipliziert. Node schreibt Arrays mit Leerzeichen in den Klammern.")
a("js35", "const z = [1, 2, 3, 4];\nconsole.log(z.reduce((summe, x) => summe + x, 0));", "10", ["10", "1234", "[1, 2, 3, 4]", "0"], "reduce sammelt alle Elemente zu einem Wert, hier die Summe.")
a("js36", "const z = [10, 1, 5];\nz.sort();\nconsole.log(z.join(\",\"));", "1,10,5", ["1,10,5", "1,5,10", "10,5,1", "10,1,5"], "sort() ohne Vergleichsfunktion sortiert als Text: \"10\" kommt vor \"5\". Richtig: z.sort((a, b) => a - b).")
a("js37", "const name = \"Lea\";\nconsole.log(`Hallo ${name}, ${2 + 3} Punkte`);", "Hallo Lea, 5 Punkte", ["Hallo Lea, 5 Punkte", "Hallo ${name}, ${2 + 3} Punkte", "Hallo Lea, 2 + 3 Punkte", "Fehler"], "In Backticks werden ${…}-Ausdrücke ausgewertet.")
a("js38", "const hund = { name: \"Rex\", alter: 3 };\nconst { name, alter } = hund;\nconsole.log(name, alter + 1);", "Rex 4", ["Rex 4", "Rex 3", "undefined undefined", "Fehler"], "Destructuring holt die Eigenschaften in gleichnamige Variablen.")
a("js39", "const a = { x: 1, y: 2 };\nconst b = { ...a, y: 5 };\nconsole.log(a.y, b.y);", "2 5", ["2 5", "5 5", "2 2", "Fehler"], "Spread kopiert a in ein neues Objekt, danach wird y überschrieben. a bleibt gleich.")
a("js40", "const liste = [1, 2];\nconst kopie = liste;\nkopie.push(3);\nconsole.log(liste.length);", "3", ["3", "2", "Fehler", "undefined"], "kopie ist keine Kopie, sondern derselbe Array. Für eine echte Kopie: [...liste].")
a("js41", "const x = [];\nx.push(1);\nconsole.log(x);", "[ 1 ]", ["[ 1 ]", "TypeError", "[]", "1"], "const verbietet nur eine neue Zuweisung. Den Array selbst darf man verändern.")
a("js42", "let n;\nconsole.log(n, n ?? \"leer\");", "undefined leer", ["undefined leer", "null leer", "undefined undefined", "Fehler"], "Ohne Wert ist n undefined. ?? liefert dann den rechten Wert.")
a("js43", "console.log(0 || \"standard\", 0 ?? \"standard\");", "standard 0", ["standard 0", "0 0", "standard standard", "0 standard"], "|| nimmt den rechten Wert bei jedem falsy-Wert (auch 0), ?? nur bei null und undefined.")
a("js44", "const user = {};\nconsole.log(user.adresse?.ort);", "undefined", ["undefined", "TypeError", "null", "\"\""], "?. bricht ab, wenn adresse fehlt, statt einen Fehler zu werfen.")
a("js45", "for (let i = 0; i < 3; i++) {\n  setTimeout(() => console.log(i), 0);\n}", "0\n1\n2", ["0\n1\n2", "3\n3\n3", "2\n1\n0", "0"], "let erzeugt pro Durchlauf eine eigene Variable i. Mit var käme dreimal 3.")
a("js46", "console.log(\"A\");\nsetTimeout(() => console.log(\"B\"), 0);\nPromise.resolve().then(() => console.log(\"C\"));\nconsole.log(\"D\");", "A\nD\nC\nB", ["A\nD\nC\nB", "A\nB\nC\nD", "A\nD\nB\nC", "A\nC\nD\nB"], "Erst der normale Code (A, D), dann Promises (C), dann Timer (B).")
a("js47", "async function laden() {\n  return 42;\n}\nladen().then(x => console.log(x + 1));", "43", ["43", "42", "Promise { 42 }", "undefined"], "Eine async-Funktion liefert ein Promise, then bekommt den Wert.")
a("js48", "function f(a, b = 10) {\n  return a + b;\n}\nconsole.log(f(5), f(5, 1));", "15 6", ["15 6", "5 6", "NaN 6", "15 15"], "b hat einen Standardwert, wenn es nicht übergeben wird.")
a("js49", "const quadrat = x => x * x;\nconsole.log([1, 2, 3].map(quadrat));", "[ 1, 4, 9 ]", ["[ 1, 4, 9 ]", "[ 2, 4, 6 ]", "14", "[ 1, 2, 3 ]"], "map ruft quadrat für jedes Element auf.")
a("js50", "console.log([1, 2, 3].includes(2), \"Hallo\".includes(\"all\"));", "true true", ["true true", "true false", "false true", "1 1"], "includes gibt es bei Arrays und Strings.")
a("js51", "console.log(Number(\"12px\"), parseInt(\"12px\"));", "NaN 12", ["NaN 12", "12 12", "NaN NaN", "12 NaN"], "Number braucht einen reinen Zahl-Text, parseInt liest so weit wie möglich.")
a("js52", "const p = { name: \"Mia\", alter: 16 };\nconsole.log(Object.keys(p).length, JSON.stringify(p));", "2 {\"name\":\"Mia\",\"alter\":16}", ["2 {\"name\":\"Mia\",\"alter\":16}", "2 {name: \"Mia\", alter: 16}", "2 [object Object]", "16 {\"name\":\"Mia\"}"], "Object.keys liefert die Schlüssel, JSON.stringify den JSON-Text ohne Leerzeichen.")
a("js53", "class Tier {\n  constructor(name) { this.name = name; }\n  laut() { return \"...\"; }\n}\nclass Katze extends Tier {\n  laut() { return `${this.name}: Miau`; }\n}\nconsole.log(new Katze(\"Luna\").laut());", "Luna: Miau", ["Luna: Miau", "...", "undefined: Miau", "Fehler"], "Katze übernimmt den Konstruktor von Tier und überschreibt laut().")
a("js54", "console.log([..."+'"abc"'+"].reverse().join(\"\"));", "cba", ["cba", "abc", "c,b,a", "Fehler"], "[...\"abc\"] zerlegt den String in Buchstaben, reverse dreht um, join setzt zusammen.")
a("js55", "console.log(Boolean(\"0\"), Boolean(\"\"), Boolean([]));", "true false true", ["true false true", "false false false", "false false true", "true false false"], "\"0\" und [] sind truthy, nur der leere String ist falsy.")

l("js70", "Ergänze, damit pi nicht neu zugewiesen werden kann.", "___ pi = 3.14;\ntry {\n  pi = 3;\n  console.log(\"geändert\");\n} catch (e) {\n  console.log(\"geschützt\");\n}", "const", ["const", "let", "var", "final"], "geschützt", "Bei const wirft eine neue Zuweisung einen TypeError. Mit let oder var wäre pi geändert. final gibt es in JavaScript nicht.")
l("js71", "Ergänze den strengen Vergleich.", "console.log(5 ___ \"5\");", "===", ["===", "==", "=", "<="], "false", "=== vergleicht auch den Typ: Zahl ist nicht gleich String.")
l("js72", "Ergänze die Methode, die ein neues Array mit umgewandelten Werten liefert.", "console.log([1, 2, 3].___(x => x + 1).join(\" \"));", "map", ["map", "forEach", "filter", "find"], "2 3 4", "map liefert ein neues Array. forEach liefert undefined.")
l("js73", "Ergänze, um hinten ein Element anzufügen.", "const l = [\"a\"];\nl.___(\"b\");\nconsole.log(l.join(\"\"));", "push", ["push", "append", "add", "unshift"], "ab", "In JavaScript heißt es push. unshift fügt vorne ein.")
l("js74", "Ergänze, um auf das Promise zu warten.", "async function start() {\n  const wert = ___ Promise.resolve(\"fertig\");\n  console.log(wert);\n}\nstart();", "await", ["await", "async", "then", "yield"], "fertig", "await wartet auf das Promise und liefert seinen Wert.")
l("js75", "Ergänze die Anführungszeichen für einen Template-String.", "const n = 3;\nconsole.log(___${n} Äpfel___);", "`", ["`", "\"", "'", "´"], "3 Äpfel", "Nur Backticks werten ${…} aus.")

speichern("javascript_grundlagen", "JavaScript Grundlagen", "javascript", "Grundlagen",
          "Variablen, Vergleiche, Arrays, Objekte, Funktionen, Destructuring, Klassen und async/await.",
          "paket_javascript")
