from gemeinsam import *

b("py01", "Wie legt man in Python eine Variable an?", "Einfach mit Name = Wert. Einen Typ muss man nicht angeben, Python erkennt ihn selbst.", "alter = 17\nname = \"Mia\"")
b("py02", "Was bedeutet die Einrückung in Python?", "Sie legt die Blöcke fest (statt geschweifter Klammern). Alles, was gleich weit eingerückt ist, gehört zusammen.")
b("py03", "Was ist der Unterschied zwischen Liste und Tupel?", "Eine Liste [1, 2] ist veränderbar, ein Tupel (1, 2) nicht.")
b("py04", "Was ist ein Dictionary?", "Eine Zuordnung Schlüssel → Wert in geschweiften Klammern.", "alter = {\"Mia\": 16, \"Tom\": 17}")
b("py05", "Was macht def?", "Definiert eine Funktion.", "def doppelt(x):\n    return x * 2")
b("py06", "Was ist None?", "Der Wert für „nichts“. Eine Funktion ohne return gibt None zurück.")
b("py07", "Was ist eine f-String?", "Ein String mit f davor, in dem man Ausdrücke in geschweiften Klammern einsetzen kann.", "print(f\"Hallo {name}, du bist {alter} Jahre alt\")")
b("py08", "Was ist der Unterschied zwischen / und //?", "/ teilt immer mit Komma (7 / 2 = 3.5), // teilt ganzzahlig und rundet ab (7 // 2 = 3).")
b("py09", "Was macht range(1, 5)?", "Erzeugt die Zahlen 1, 2, 3, 4. Das Ende ist nicht enthalten.")
b("py10", "Was ist eine List Comprehension?", "Eine kurze Schreibweise, um aus einer Folge eine neue Liste zu bauen.", "quadrate = [x * x for x in range(5)]")
b("py11", "Was macht try/except?", "Fängt Fehler (Exceptions) ab, damit das Programm nicht abstürzt.")
b("py12", "Was ist self in einer Klasse?", "Der Verweis auf das aktuelle Objekt. Er ist immer der erste Parameter von Methoden.")
b("py13", "Was macht __init__?", "Der Konstruktor einer Klasse: wird beim Erzeugen eines Objekts aufgerufen und setzt die Startwerte.")
b("py14", "Was ist ein Set?", "Eine ungeordnete Sammlung ohne Duplikate: {1, 2, 3}.")
b("py15", "Was macht import?", "Lädt ein Modul, z. B. import math, und macht seine Funktionen verfügbar (math.sqrt(16)).")
b("py16", "Was ist der Unterschied zwischen == und is?", "== vergleicht den Wert, is prüft, ob es dasselbe Objekt ist. Für None benutzt man is: if x is None.")

a("py30", "print(7 / 2, 7 // 2, 7 % 2)", "3.5 3 1", ["3.5 3 1", "3 3 1", "3.5 3.5 1", "3 3.5 1"], "/ teilt mit Komma, // ganzzahlig, % ist der Rest.")
a("py31", "print(2 ** 5)", "32", ["32", "10", "25", "7"], "** ist Potenz: 2 hoch 5.")
a("py32", "print(\"ab\" * 3)", "ababab", ["ababab", "ab3", "Fehler", "ab ab ab"], "Ein String mal eine Zahl wiederholt den String.")
a("py33", "liste = [10, 20, 30, 40]\nprint(liste[-1])", "40", ["40", "10", "Fehler", "30"], "Negative Indizes zählen von hinten: -1 ist das letzte Element.")
a("py34", "liste = [10, 20, 30, 40, 50]\nprint(liste[1:3])", "[20, 30]", ["[20, 30]", "[20, 30, 40]", "[10, 20, 30]", "[30]"], "Slicing [1:3] nimmt Index 1 und 2, das Ende ist nicht dabei.")
a("py35", "text = \"Python\"\nprint(text[::-1])", "nohtyP", ["nohtyP", "Python", "P", "Fehler"], "[::-1] geht mit Schrittweite -1 rückwärts durch den String.")
a("py36", "zahlen = [3, 1, 2]\nzahlen.append(5)\nzahlen.sort()\nprint(zahlen)", "[1, 2, 3, 5]", ["[1, 2, 3, 5]", "[3, 1, 2, 5]", "[5, 3, 2, 1]", "None"], "append hängt hinten an, sort sortiert die Liste selbst.")
a("py37", "zahlen = [3, 1, 2]\nergebnis = zahlen.sort()\nprint(ergebnis)", "None", ["None", "[1, 2, 3]", "[3, 1, 2]", "Fehler"], "sort() sortiert die Liste selbst und gibt None zurück. sorted(zahlen) würde eine neue Liste liefern.")
a("py38", "print([x * 2 for x in range(4)])", "[0, 2, 4, 6]", ["[0, 2, 4, 6]", "[2, 4, 6, 8]", "[0, 1, 2, 3]", "[0, 2, 4, 6, 8]"], "range(4) ist 0, 1, 2, 3, jedes wird verdoppelt.")
a("py39", "print([x for x in range(10) if x % 3 == 0])", "[0, 3, 6, 9]", ["[0, 3, 6, 9]", "[3, 6, 9]", "[0, 3, 6]", "[1, 4, 7]"], "Die Bedingung behält nur Vielfache von 3. Auch 0 ist ein Vielfaches.")
a("py40", "alter = {\"Mia\": 16, \"Tom\": 17}\nalter[\"Lea\"] = 15\nprint(len(alter))", "3", ["3", "2", "6", "Fehler"], "Ein neuer Schlüssel fügt einen Eintrag hinzu.")
a("py41", "alter = {\"Mia\": 16}\nprint(alter.get(\"Tom\", 0))", "0", ["0", "None", "KeyError", "16"], "get liefert den Ersatzwert, wenn der Schlüssel fehlt. alter[\"Tom\"] würde einen KeyError werfen.")
a("py42", "def gruss(name, gruss=\"Hallo\"):\n    return f\"{gruss}, {name}!\"\n\nprint(gruss(\"Ben\"))", "Hallo, Ben!", ["Hallo, Ben!", "Ben, Hallo!", "None", "Fehler"], "gruss hat einen Standardwert und muss nicht übergeben werden.")
a("py43", "def f(x):\n    x.append(4)\n\nliste = [1, 2, 3]\nf(liste)\nprint(liste)", "[1, 2, 3, 4]", ["[1, 2, 3, 4]", "[1, 2, 3]", "None", "Fehler"], "Listen werden nicht kopiert. Die Funktion verändert dieselbe Liste.")
a("py44", "a = [1, 2]\nb = a\nb.append(3)\nprint(a)", "[1, 2, 3]", ["[1, 2, 3]", "[1, 2]", "[3]", "Fehler"], "b ist kein neues Objekt, sondern ein zweiter Name für dieselbe Liste.")
a("py45", "for i in range(3):\n    print(i, end=\" \")", "0 1 2", ["0 1 2", "1 2 3", "0 1 2 3", "0\n1\n2"], "end=\" \" ersetzt den Zeilenumbruch durch ein Leerzeichen. (Das letzte Leerzeichen sieht man nicht.)")
a("py46", "x = 0\nwhile x < 10:\n    x += 4\nprint(x)", "12", ["12", "8", "10", "4"], "x: 0, 4, 8, 12. Bei 12 endet die Schleife.")
a("py47", "print(bool(\"\"), bool(\"0\"), bool(0))", "False True False", ["False True False", "False False False", "True True False", "False True True"], "Leere Strings und 0 sind falsch. \"0\" ist ein nicht leerer String und deshalb wahr.")
a("py48", "print(\"Hallo Welt\".split())", "['Hallo', 'Welt']", ["['Hallo', 'Welt']", "Hallo Welt", "['Hallo Welt']", "('Hallo', 'Welt')"], "split() ohne Argument trennt an Leerzeichen und liefert eine Liste.")
a("py49", "print(\"-\".join([\"a\", \"b\", \"c\"]))", "a-b-c", ["a-b-c", "-a-b-c", "abc", "['a', 'b', 'c']"], "join verbindet die Elemente mit dem Trenner davor.")
a("py50", "print(len({1, 2, 2, 3, 3, 3}))", "3", ["3", "6", "1", "Fehler"], "Ein Set speichert jeden Wert nur einmal.")
a("py51", "x, y = 1, 2\nx, y = y, x\nprint(x, y)", "2 1", ["2 1", "1 2", "2 2", "Fehler"], "Tupel-Zuweisung tauscht die Werte in einem Schritt.")
a("py52", "try:\n    print(10 / 0)\nexcept ZeroDivisionError:\n    print(\"geht nicht\")\nfinally:\n    print(\"fertig\")", "geht nicht\nfertig", ["geht nicht\nfertig", "fertig", "inf\nfertig", "geht nicht"], "Durch 0 teilen wirft einen Fehler, except fängt ihn, finally läuft immer.")
a("py53", "class Hund:\n    def __init__(self, name):\n        self.name = name\n\n    def bellen(self):\n        return self.name + \": Wuff\"\n\nprint(Hund(\"Rex\").bellen())", "Rex: Wuff", ["Rex: Wuff", "Wuff", "self.name: Wuff", "Fehler"], "__init__ speichert den Namen, die Methode greift über self darauf zu.")
a("py54", "zahlen = [5, 2, 8]\nprint(max(zahlen) - min(zahlen), sum(zahlen))", "6 15", ["6 15", "3 15", "6 5", "8 2"], "max 8, min 2, Summe 15.")
a("py55", "for i, buchstabe in enumerate(\"ab\"):\n    print(i, buchstabe)", "0 a\n1 b", ["0 a\n1 b", "1 a\n2 b", "a 0\nb 1", "0 1"], "enumerate liefert Paare aus Index und Element.")
a("py56", "namen = [\"Mia\", \"Tom\"]\nalter = [16, 17]\nprint(dict(zip(namen, alter)))", "{'Mia': 16, 'Tom': 17}", ["{'Mia': 16, 'Tom': 17}", "[('Mia', 16), ('Tom', 17)]", "{'Mia': 'Tom', 16: 17}", "Fehler"], "zip verbindet zwei Listen paarweise, dict macht daraus ein Dictionary.")
a("py57", "def f():\n    pass\n\nprint(f())", "None", ["None", "pass", "", "Fehler"], "Ohne return gibt eine Funktion None zurück.")
a("py58", "print(round(2.5), round(3.5))", "2 4", ["2 4", "3 4", "2 3", "3 3"], "Python rundet bei .5 zur nächsten geraden Zahl (Bankers Rounding).")
a("py59", "print(sorted([\"banane\", \"Apfel\", \"kiwi\"], key=len))", "['kiwi', 'Apfel', 'banane']", ["['kiwi', 'Apfel', 'banane']", "['Apfel', 'banane', 'kiwi']", "['banane', 'Apfel', 'kiwi']", "['Apfel', 'kiwi', 'banane']"], "key=len sortiert nach der Länge: 4, 5, 6.")
a("py60", "zahl = 15\nif zahl % 3 == 0 and zahl % 5 == 0:\n    print(\"FizzBuzz\")\nelif zahl % 3 == 0:\n    print(\"Fizz\")\nelse:\n    print(zahl)", "FizzBuzz", ["FizzBuzz", "Fizz", "15", "Buzz"], "15 ist durch 3 und 5 teilbar, die erste passende Bedingung gewinnt.")

l("py80", "Ergänze das Schlüsselwort für eine Funktion.", "___ quadrat(x):\n    return x * x\n\nprint(quadrat(5))", "def", ["def", "function", "fun", "func"], "25", "In Python werden Funktionen mit def definiert.")
l("py81", "Ergänze, damit eine Zahl eingesetzt wird.", "punkte = 42\nprint(___\"Du hast {punkte} Punkte\")", "f", ["f", "r", "b", "s"], "Du hast 42 Punkte", "Nur f-Strings setzen Ausdrücke in {} ein.")
l("py82", "Ergänze, um ein Element hinten anzuhängen.", "liste = [1, 2]\nliste.___(3)\nprint(liste)", "append", ["append", "add", "push", "insert"], "[1, 2, 3]", "Listen haben append. add gibt es bei Sets, push in JavaScript.")
l("py83", "Ergänze den Fehler-Typ.", "try:\n    zahl = int(\"abc\")\nexcept ___:\n    print(\"keine Zahl\")", "ValueError", ["ValueError", "TypeError", "KeyError", "IndexError"], "keine Zahl", "int(\"abc\") wirft einen ValueError: Der Typ stimmt (String), der Wert nicht.")
l("py84", "Ergänze, damit 1 bis 3 ausgegeben werden.", "for i in range(1, ___):\n    print(i, end=\"\")", "4", ["4", "3", "5", "2"], "123", "Das Ende von range ist nicht enthalten.")
l("py85", "Ergänze den ersten Parameter der Methode.", "class Zaehler:\n    def __init__(self):\n        self.n = 0\n\n    def plus(___):\n        self.n += 1\n\nz = Zaehler()\nz.plus()\nprint(z.n)", "self", ["self", "this", "me", "obj"], "1", "Methoden bekommen das Objekt als ersten Parameter, Konvention: self.")
l("py86", "Ergänze, um durch alle Paare eines Dictionarys zu gehen.", "preise = {\"Apfel\": 1, \"Kiwi\": 2}\nfor name, preis in preise.___():\n    print(name, preis)", "items", ["items", "keys", "values", "pairs"], "Apfel 1\nKiwi 2", "items() liefert Paare aus Schlüssel und Wert.")

speichern("python_grundlagen", "Python Grundlagen", "python", "Grundlagen",
          "Variablen, Listen, Dictionaries, Schleifen, Funktionen, f-Strings, Fehler und Klassen.",
          "paket_python")
